/**
 * This file was generated by the Jeddict
 */
package test;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * @author rupak
 */
@Entity
public class Customer extends Person {

    @ManyToOne(targetEntity = Employee.class)
    private Employee primaryContact;

    @OneToMany(targetEntity = ProductOrder.class)
    private List<ProductOrder> productOrders;

    public Employee getPrimaryContact() {
        return this.primaryContact;
    }

    public void setPrimaryContact(Employee primaryContact) {
        this.primaryContact = primaryContact;
    }

    public List<ProductOrder> getProductOrders() {
        return this.productOrders;
    }

    public void setProductOrders(List<ProductOrder> productOrders) {
        this.productOrders = productOrders;
    }

}